### ISSUE TITLE
Upgrade panel is showing worng status

### ISSUE THREAD

**Issue by Danilll01** [Danilll01/TDA367-OO-Projekt#34]
When a tower of upgrade level 3 is selcted and a new tower is being dragged out from tower drawer the upgrade panel shows wrong information. 

Possible fix is to look over if statements when rendering upgrade panel

![image](https://user-images.githubusercontent.com/59963395/136410901-62283ce5-80bd-48a8-84ae-05d19646b760.png)

**Comment by Turbobus** [comment]
The bug was a result of not reseting the disabled button status if the upgrade was bought. This resulted in the previus "disabled" state beeing showed instead of actual one.

**Comment by Turbobus** [comment]
The fix was to reset the disabled status when the second upgrade was bought.
